[package]
name = "rg-sens-audio"
version = "0.7.6"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Audio playback for rg-Sens alarms and timers"

[dependencies]
rg-sens-types = { path = "../types" }
anyhow = "1"
rodio = "0.19"
serde = { version = "1", features = ["derive"] }
